### ISSUE TITLE
Where is this package on conda?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-iers-data#12]
You mentioned grabbing this from `conda` over at `astropy` (https://github.com/astropy/astropy/pull/14819) but where is the feedstock? How do we make sure the conda version won't fall behind? If no one diligently merge the conda feedstock updates, it is going to fall behind.

**Comment by astrofrog** [comment]
We need to set this up at conda forge and we should enable auto merging of automatic update PRs (it's an option)

**Comment by pllim** [comment]
Is this something @mwcraig can help with?

**Comment by astrofrog** [comment]
I've added the recipe here: https://github.com/conda-forge/staged-recipes/pull/23209
