### ISSUE TITLE
Automate GitHub release and Zenodo

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-iers-data#15]
Once https://github.com/astropy/astropy-iers-data/pull/13 is merged I need to try and see if we can automate the GitHub release + Zenodo step.

**Comment by pllim** [comment]
I would be interested in how you do it if you can get it to work!

**Comment by astrofrog** [comment]
Done! The workflow now includes a create release step, and I have just triggered a new release:

https://github.com/astropy/astropy-iers-data/actions/runs/5480489048
https://github.com/astropy/astropy-iers-data/releases/tag/v0.2023.07.06.22.03.16
https://zenodo.org/record/8122413

Seems to work!
