### ISSUE TITLE
Tags are inconsistent with PyPI versions

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-iers-data#17]
`v0.2023.07.31.00.32.45` in https://github.com/astropy/astropy-iers-data/tags is released as `0.2023.7.31.0.32.45` on https://pypi.org/project/astropy-iers-data/#history . Kinda confusing.

**Comment by astrofrog** [comment]
Interesting, I wonder at what point the leading zeros get stripped - will need to investigate!

**Comment by sergiopasra** [comment]
I'm trying to build Fedora packages automatically after release and this discrepancy is stopping me. Please check my PR

**Comment by astrofrog** [comment]
@sergiopasra I'm not sure if this worked, see latest version on PyPI

**Comment by sergiopasra** [comment]
> @sergiopasra I'm not sure if this worked, see latest version on PyPI

It's strange. 

If I run `python -m setuptools_scm` in a cloned repo I get:

0.2024.8.27.10.28.30.dev1+g64350ba.d20240827

if `normalize = true` or unset and:

v0.2024.08.27.10.28.30.dev1+g64350ba

if `normalize = false`

It's not only the "0", there is also a "v" from the tag.

**Comment by sergiopasra** [comment]
Setuptools is normalizing the version. Look, for example https://github.com/astropy/astropy-iers-data/actions/runs/10576259768/job/29302037025#step:7:288

**Comment by sergiopasra** [comment]
This was reported and a solution was inplemented, but it is not applicable with current standards (builds without `setup.py`)

https://github.com/pypa/setuptools/issues/308

**Comment by astrofrog** [comment]
The next best option is to change the tags so that they are identical to the setuptools normalised version

**Comment by pllim** [comment]
OK let's reopen since this is still a problem. Thanks!

**Comment by pllim** [comment]
Now looks good. Thanks!

* GitHub: `v0.2024.9.12.13.29.57`
* PyPI: `0.2024.9.12.13.29.57`
