### ISSUE TITLE
Improve auto-update workflow

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-iers-data#5]
Currently when the auto-update PRs are opened, because they are opened from @github-actions, the CI does not run. We need to manually close and re-open the PR. We could get around this by using a personal access token instead of the usual ``GITHUB_TOKEN`` token but these expire at most after a year so need to be updated manually. We should think about how we could improve this workflow.

**Comment by pllim** [comment]
Close/reopen isn't that much of an overhead, so maybe a note for the maintainers from the auto-update bot that this needs to be done is enough? I can see why GitHub put in this safeguard as annoying as it is.

**Comment by astrofrog** [comment]
I've already updated the workflow so that the PR description mentions the workaround so hopefully that will help.
