### ISSUE TITLE
TST: Point to canonical astropy

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-iers-data#9]
Just a reminder issue for this:

https://github.com/astropy/astropy-iers-data/blob/d29c3b651f0e8ce8cf286982fca08860f6cfced7/tox.ini#L10C4-L11

Also probably need to test both stable and dev astropy? Or is that overkill?

**Comment by astrofrog** [comment]
I think stable is fine as the dev astropy build in astropy should be enough?

**Comment by pllim** [comment]
Fixed in  600bb782b71650e9965620155530f3b239ef939b
